GET http://localhost:8080/api/fcf2a83a-8669-11eb-8dcd-0242ac130003

###
POST http://localhost:8080/api/save/
Content-Type: application/json

{
  "id": "",
  "engineType": "V10",
  "oilReplSystem": true,
  "divValveDuplFilter": true,
  "duplFuelFilter": false,
  "divValveFuelFilter": true,
  "fuelLeakageMonitor": true
}

###

GET http://localhost:8080/api/all/

###

POST http://localhost:18080/api/analyse/
Content-Type: application/json

{
  "id": "",
  "engineType": "V10",
  "oilReplSystem": true,
  "divValveDuplFilter": true,
  "duplFuelFilter": false,
  "divValveFuelFilter": true,
  "fuelLeakageMonitor": true
}

###
POST http://localhost:18082/analyse1/
Content-Type: application/json

{
  "id": "",
  "engineType": "V10",
  "oilReplSystem": true,
  "divValveDuplFilter": true,
  "duplFuelFilter": false,
  "divValveFuelFilter": true,
  "fuelLeakageMonitor": true
}

###

GET http://localhost:8081/

###

GET http://analyse-service1/

###
POST http://localhost:8084/save
Content-Type: application/json

{
  "id": "",
  "engineType": "V10",
  "oilReplSystem": true,
  "divValveDuplFilter": true,
  "duplFuelFilter": false,
  "divValveFuelFilter": true,
  "fuelLeakageMonitor": true,
  "timestamp": null,
  "successful1": true,
  "successful2": null
}

###
GET http://localhost:8085/config/get/7022a50e-ba13-4bd7-b23c-4b7ab88e0a17

###
GET http://localhost:8085/config/get/all

###
GET http://localhost:8081/actuator/health/working

###
GET http://localhost:8082/actuator/health/working

###
GET http://localhost:8081/state

###
GET http://localhost:18082/

###
GET http://localhost:8084/get/8b0170d8-7440-44b5-98c2-fdb4142bb687

###