GET http://localhost:8080/fcf2a83a-8669-11eb-8dcd-0242ac130003

###
POST http://localhost:8080/
Content-Type: application/json

{
  "id": "",
  "engineType": "V10",
  "oilReplSystem": true,
  "divValveDuplFilter": true,
  "duplFuelFilter": false,
  "divValveFuelFilter": true,
  "fuelLeakageMonitor": true
}

###