version: '3.8'
services:
  service-registry:
    container_name: service-registry
    build:
      context: service-registry
      dockerfile: Dockerfile
    image: ooka-service-registry:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    depends_on:
      - service-registry
    image: ooka-api-gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 18080:8080
    networks:
      - spring-cloud-network
  manufacturing-service:
    container_name: manufacturing-service
    build:
      context: manufacturing-service
      dockerfile: Dockerfile
    depends_on:
      - service-registry
    image: ooka-manufacturing-service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 18086:8084
    networks:
      - spring-cloud-network
  analyse-service1:
    container_name: analyse-service1
    build:
      context: analyse-service1
      dockerfile: Dockerfile
    depends_on:
      - service-registry
    image: ooka-analyse-service1:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 18081-18082:8081
    networks:
      - spring-cloud-network
  analyse-service2:
    container_name: analyse-service2
    build:
      context: analyse-service2
      dockerfile: Dockerfile
    depends_on:
      - service-registry
    image: ooka-analyse-service2:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 18083-18084:8082
    networks:
      - spring-cloud-network
  persistency-service:
    container_name: persistency-service
    build:
      context: persistency-service
      dockerfile: Dockerfile
    depends_on:
      - service-registry
    image: ooka-persistency-service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 18085:8085
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge